version: "3.9"

services:
  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - grpc-microservice-volume:/var/lib/mysql
    networks:
      - grpc-microservices-net
  customer-grpc-server:
    container_name: customer-grpc-server
    image: customer-grpc-app:1.0.0
    ports:
      - "50051:50051"
    depends_on:
      mysql:
        condition: service_started
    networks:
      - grpc-microservices-net
  grpc-rest-api:
    container_name: grpc-rest-api
    image: grpc-rest-api:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - customer-grpc-server
    networks:
      - grpc-microservices-net

networks:
  grpc-microservices-net:
    name: grpc-microservices-net
    external: true

volumes:
  grpc-microservice-volume:
    name: grpc-microservice-volume
    external: true