openapi: 3.0.3
info:
  title: Microservice with Go and gRPC
  description: API Specification for learning microservice with grpc
  version: 1.0.0
  contact:
    email: billyimmcul2010@gmail.com
    name: Billy Kore
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: auth
    description: Authorization operation
  - name: customer
    description: Customer account operation
  - name: payment
    description: Payment operation
paths:
  /auth/token:
    description: API endpoint for get access token
    post:
      tags:
        - auth
      summary: Get access token
      requestBody:
        description: Get token request
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        '200':
          description: Success get token
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 200
                  responseMessage:
                    type: string
                    example: Success get token
                  data:
                    type: object
                    example:
                      token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjc0MDQ0MTY5LCJpYXQiOjE2NzQwNDMyNjl9.JINtov_hySXKiPoJ8_mst3YbCEla0KCW5aZynD7md4g'
                      tokenType: Bearer token
                      expiresIn: 900
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 400
                  responseMessage:
                    type: string
                    example: Failed get token
                  error:
                    type: string
                    example: Unsupported grant type
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 401
                  responseMessage:
                    type: string
                    example: Failed get token
                  error:
                    type: string
                    example: Invalid username or password
  /account/create:
    description: API endpoint for create new customer account
    post:
      tags:
        - customer
      summary: Create new customer account
      requestBody:
        description: Create new customer account request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Success create new customer account
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 200
                  responseMessage:
                    type: string
                    example: Account creation success
        '503':
          description: Account service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 503
                  responseMessage:
                    type: string
                    example: Account creation failed
                  error:
                    type: string
                    example: Account service unavailable. Please try again later
  /account/inquiry:
    description: API endpoint for inquiry customer account
    get:
      tags:
        - customer
      summary: Inquiry customer account by account number
      parameters:
        - name: accountNumber
          in: query
          description: Account Number of customer account to return
          required: true
          schema:
            type: string
            example: '001001000002300'
      responses:
        '200':
          description: Success inquiry customer account
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 200
                  responseMessage:
                    type: string
                    example: Customer account inquiry success
                  data:
                    type: object
                    example:
                      cif: '0000000003'
                      accountNumber: '001001000002300'
                      accountType: S
                      name: FLORENCE FEDORA AGUSTINA
                      currency: IDR
                      status: '1'
                      blocked: '0'
                      balance: '10000000.00'
                      minimumBalance: '0.00'
                      productType: '000005'
        '400':
          description: Missing Query Parameter
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 400
                  responseMessage:
                    type: string
                    example: 'Missing query parameter: accountNumber'
        '404':
          description: Customer account not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 404
                  responseMessage:
                    type: string
                    example: Customer account not found
        '503':
          description: Account service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 503
                  responseMessage:
                    type: string
                    example: Customer account inquiry failed
                  error:
                    type: string
                    example: Account service unavailable. Please try again later
  /payment/qris:
    description: API endpoint for qris payment
    post:
      tags:
        - payment
      summary: Qris payment
      requestBody:
        description: Qris payment request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QrisRequest'
      responses:
        '200':
          description: Qris payment successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 200
                  responseMessage:
                    type: string
                    example: Qris payment successful
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 404
                  responseMessage:
                    type: string
                    example: Failed to process qris payment
                  error:
                    type: string
                    example: Request body is not valid
        '503':
          description: Payment service unavailable
          content:
            application/json:
              schema:
                type: object
                properties:
                  responseCode:
                    type: integer
                    example: 503
                  responseMessage:
                    type: string
                    example: Failed to process qris payment
                  error:
                    type: string
                    example: Payment service unavailable. Please try again later
components:
  schemas:
    TokenRequest:
      type: object
      properties:
        username:
          type: string
          example: oyenmakanikan
        password:
          type: string
          example: very_secret_password_duh
        grantType:
          type: string
          example: password
    Customer:
      type: object
      properties:
        nik:
          type: string
          example: '0101013102000001'
        name:
          type: string
          example: Ni Luh Putu Giri Gita Saraswati
        pob:
          type: string
          example: Jakarta
        dob:
          type: string
          example: 13/03/2003
        address:
          type: string
          example: Jakarta
        profession:
          type: string
          example: Engineer
        gender:
          type: string
          example: Female
        religion:
          type: string
          example: Hindu
        marriageStatus:
          type: string
          example: NotMarried
        citizen:
          type: string
          example: WNI
    QrisRequest:
      type: object
      properties:
        merchantId:
          type: string
          example: 'M-001'
        trxNumber:
          type: string
          example: '0000001'
        accountSource:
          type: string
          example: '001001000001300'
        accountDestination:
          type: string
          example: '001001000002300'
        amount:
          type: string
          example: '500000'
